-- MySQL Script generated by MySQL Workbench
-- 02/10/16 10:11:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fiveware
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiveware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiveware` DEFAULT CHARACTER SET utf8 ;
USE `fiveware` ;

-- -----------------------------------------------------
-- Table `fiveware`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiveware`.`area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiveware`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiveware`.`skill` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_area` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_SKILL_AREA_idx` (`id_area` ASC),
  CONSTRAINT `FK_SKILL_AREA`
    FOREIGN KEY (`id_area`)
    REFERENCES `fiveware`.`area` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiveware`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiveware`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthdate` DATETIME NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL,
  `id_area` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_AREA_SKILL_idx` (`id_area` ASC),
  CONSTRAINT `FK_USER_AREA`
    FOREIGN KEY (`id_area`)
    REFERENCES `fiveware`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiveware`.`user_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiveware`.`user_skill` (
  `id_skill` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id_skill`, `id_user`),
  INDEX `FK_USER_SKILL_USER_idx` (`id_user` ASC),
  INDEX `FK_USER_SKILL_SKILL_idx` (`id_skill` ASC),
  CONSTRAINT `FK_USER_SKILL_SKILL`
    FOREIGN KEY (`id_skill`)
    REFERENCES `fiveware`.`skill` (`id`),
  CONSTRAINT `FK_USER_SKILL_USER`
    FOREIGN KEY (`id_user`)
    REFERENCES `fiveware`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
